### PR TITLE
Aflal

### PR DESCRIPTION
**Pull request by Af1a1**

### CODE REVIEW

**Review by mahadi-devo — DISMISSED** [review]

**Review by mahadi-devo — COMMENTED** [review]
add research UI

**Review by mahadi-devo — DISMISSED** [review]

**Comment by mahadi-devo** [comment]
> _No description provided._

Resolve conflicts

**Comment by mahadi-devo** [comment]
Resolve conflicts and pull again

**Comment by Af1a1** [comment]
ok

**Pull request closed without merging**
